lane :beta do
    gym(scheme: "AppScheme",
    #output_name 指打包完成后, 输出ipa文件的名字
    output_name: "APPName_Debug",
    #export_method 打包版本选择
    #分别是app-store、ad-hoc、development、enterprise
    export_method: "ad-hoc",
        export_options: {
          provisioningProfiles: { 
          #左侧表示你的项目的bundle id
          #右侧表示你的项目在选择export_method后,对应的描述文件名字
          "com.d2eam.JenkinsTest" => "JenkinsAdHocTest_D2eam"
        }
       }) 
  end
